spring:
  application:
    name: raft

server:
  port: 8080
  shutdown: graceful

grpc:
  server:
    port: 9090

alg.raft:
  heartbeat-interval-ms: 1000
  election:
    min-timeout-ms: 4000
    max-timeout-ms: 10000
  compaction:
    threshold: 100
  membership:
    configuration-on-rpc-error: true # rpc 통신에서 오류가 발생한 경우 configuration 로그 생성 여부